# Generated by Django 5.0.1 on 2024-04-12 02:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team1", models.CharField(max_length=64)),
                ("team2", models.CharField(max_length=64)),
                ("spread1", models.CharField(max_length=64)),
                ("spread2", models.CharField(max_length=64)),
                ("win1", models.CharField(max_length=64)),
                ("win2", models.CharField(max_length=64)),
                ("total1", models.CharField(max_length=64)),
                ("total2", models.CharField(max_length=64)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="LolSpread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team1", models.CharField(max_length=64)),
                ("team2", models.CharField(max_length=64)),
                ("spread1_decimal", models.FloatField(max_length=64)),
                ("spread2_decimal", models.FloatField(max_length=64)),
                ("spread1_ou", models.FloatField(max_length=16)),
                ("spread2_ou", models.FloatField(max_length=16)),
                ("spread1_probability", models.IntegerField()),
                ("spread2_probability", models.IntegerField()),
                ("spread1_ev", models.FloatField(max_length=64)),
                ("spread2_ev", models.FloatField(max_length=64)),
                ("spread1_site", models.CharField(max_length=64)),
                ("spread2_site", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="LolTotal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team1", models.CharField(max_length=64)),
                ("team2", models.CharField(max_length=64)),
                ("total1_decimal", models.FloatField(max_length=64)),
                ("total2_decimal", models.FloatField(max_length=64)),
                ("total1_over", models.FloatField(max_length=16)),
                ("total2_over", models.FloatField(max_length=16)),
                ("total1_probability", models.IntegerField()),
                ("total2_probability", models.IntegerField()),
                ("total1_ev", models.FloatField(max_length=64)),
                ("total2_ev", models.FloatField(max_length=64)),
                ("total1_site", models.CharField(max_length=64)),
                ("total2_site", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="LolWin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team1", models.CharField(max_length=64)),
                ("team2", models.CharField(max_length=64)),
                ("win1_decimal", models.FloatField(max_length=64)),
                ("win2_decimal", models.FloatField(max_length=64)),
                ("win1_probability", models.IntegerField()),
                ("win2_probability", models.IntegerField()),
                ("win1_ev", models.FloatField(max_length=64)),
                ("win2_ev", models.FloatField(max_length=64)),
                ("win1_site", models.CharField(max_length=64)),
                ("win2_site", models.CharField(max_length=64)),
            ],
        ),
    ]
