# Generated by Django 5.0.1 on 2024-04-12 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("esports", "0002_rename_total2_over_loltotal_total2_under"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loltotal", old_name="total1_over", new_name="total_over",
        ),
        migrations.RenameField(
            model_name="loltotal", old_name="total2_under", new_name="total_under",
        ),
    ]
