# Generated by Django 5.0.1 on 2024-04-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esports", "0003_rename_total1_over_loltotal_total_over_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lolspread",
            name="date",
            field=models.CharField(default="2024", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="loltotal",
            name="date",
            field=models.CharField(default="2024", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lolwin",
            name="date",
            field=models.CharField(default="2024", max_length=64),
            preserve_default=False,
        ),
    ]
